name: Artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: git submodule update --init --recursive
    - run: mkdir -p artifacts/plugin.video.iptv.magiogo
    - run: cp -r magio/ artifacts/plugin.video.iptv.magiogo
    - run: cp -r iptv/ artifacts/plugin.video.iptv.magiogo
    - run: rm -r artifacts/plugin.video.iptv.magiogo/iptv/.github
    - run: rm artifacts/plugin.video.iptv.magiogo/iptv/.git artifacts/plugin.video.iptv.magiogo/iptv/.gitignore
    - run: cp -r resources/ artifacts/plugin.video.iptv.magiogo
    - run: cp LICENSE artifacts/plugin.video.iptv.magiogo
    - run: cp icon.png artifacts/plugin.video.iptv.magiogo
    - run: cp main.py artifacts/plugin.video.iptv.magiogo
    - run: cp service.py artifacts/plugin.video.iptv.magiogo
    - run: cp addon.xml artifacts/plugin.video.iptv.magiogo
    - run: cp readme.md artifacts/plugin.video.iptv.magiogo
    - uses: actions/upload-artifact@v1
      with:
        name: plugin.video.iptv.magiogo
        path: artifacts
